name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt static site
        run: npm run generate

      - name: Verify build output
        run: |
          if [ ! -d ".output/public" ]; then
            echo "ERROR: .output/public not found!"
            exit 1
          fi
          ls -la .output/public

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: ".output/public/*"
          remote_path: "/"
          sftp_only: true
