name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Pull repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Nuxt static site
      - name: Build Nuxt site
        run: npm run generate

      # Verify build output exists
      - name: Verify build output
        run: |
          if [ ! -d ".output/public" ]; then
            echo "ERROR: .output/public not found!"
            exit 1
          fi
          echo "Build output found:"
          ls -la .output/public

      # Deploy to IONOS via SFTP (from inside public folder)
      - name: Deploy via SFTP
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.FTP_SERVER }}
          remote-user: ${{ secrets.FTP_USERNAME }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          remote-path: "/"
          local-folder: "."
          sync: "full"
          working-directory: .output/public
