name: Deploy to IONOS via SCP (Full Deploy)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Nuxt static site
      - name: Build Nuxt site
        run: npm run generate

      # Verify build output exists
      - name: Verify build output
        run: |
          if [ ! -d ".output/public" ]; then
            echo "ERROR: .output/public not found!"
            exit 1
          fi
          echo "Build output found:"
          ls -la .output/public

      # Deploy via SCP (SFTP mode)
      - name: Deploy via SCP
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .output/public/
          remote: /
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          connectionTimeout: 20000
