name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt site
        run: npm run generate

      - name: Deploy via SFTP
        uses: pressidium/lftp-deploy@v1.0.0
        with:
          user: ${{ secrets.FTP_USERNAME }}
          host: ${{ secrets.FTP_SERVER }}
          pass: ${{ secrets.FTP_PASSWORD }}
          port: 22
          localDir: .output/public
          remoteDir: /htdocs
          args: --verbose --only-newer
