name: Deploy to IONOS via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      # Pull repo
      - name: Check out repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Nuxt static site
      - name: Build Nuxt site
        run: npm run generate

      # Deploy via FTP
      - name: Deploy to IONOS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .output/public/
          server-dir: /htdocs/
          protocol: ftps
          state-name: .ftp-deploy-sync-state.json
