name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt static site
        run: npm run generate

      - name: Deploy via SFTP (password auth)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: .output/public/*
          remote_path: /htdocs/
          delete_remote_files: false
