name: Deploy to IONOS via SFTP (Raw Copy)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Nuxt static site
      - name: Build Nuxt site
        run: npm run generate

      # Debug paths to confirm build output exists
      - name: Debug build paths
        run: |
          echo "PWD: $(pwd)"
          echo "Repo root contents:"
          ls -la
          echo ".output contents:"
          ls -la .output || echo "No .output folder!"
          echo ".output/public contents:"
          ls -la .output/public || echo "No .output/public folder!"

      # Deploy via raw SCP/SFTP
      - name: Deploy via SCP (SFTP mode)
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .output/public/
          remote: /
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
